apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: angularapp-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angular
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular
    spec: 
      containers: 
      - name: angular-app-kubernetes
        image: mydemo1.azurecr.io/psaywan/angular-app-kubernetes:#{Build.BuildNumber}#
        ports: 
        - containerPort: 80
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angularapp-service 
spec: 
  selector: 
    app: angularapp
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 
  type: LoadBalancer 
