apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: angularapp-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angularapp
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angularapp
    spec: 
      containers: 
      - name: angularapp
        image: mydemo1.azurecr.io/angularapp:#{Build.BuildNumber}#
        ports: 
        - containerPort: 8083 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angularapp-service 
spec: 
  selector: 
    app: angularapp
  ports: 
  - protocol: TCP 
    port: 8083 
    targetPort: 8083 
  type: LoadBalancer 
