apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angulr-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angulr 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angulr 
    spec: 
      containers: 
      - name: angular-app-kubernetes 
        image: mydemo1.azurecr.io/psaywan/angular-app-kubernetes:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
          protocol: TCP
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angulr-service 
spec: 
  selector: 
    app: angulr 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    name: grpc
  type: LoadBalancer 
